### ISSUE TITLE
Copy registry database from NERSC to CSD3

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/csd3_uk_tasks#4]
Once Postgres is up and running at CSD3, we need to copy some of the data stored in the Postgres registry database at NERSC into the new Postgres database running at CSD3.

[Jim started a discussion](https://lsstc.slack.com/archives/C01FBUGM2CV/p1730315941054799) about the technical details on Slack #dm-middleware-support.

**Comment by jchiang87** [comment]
Steps for rebuilding the `roman-desc-sims` data repository at CSD3:

- [x] Generate export yaml files from `/repo/roman-desc-sims` at NERSC using a special export script in which the data transfer functionality is disabled (since we have already copied those data by hand to CSD3) and copy those yaml files to CSD3.
- [x] Re-organize the folders at CSD3 containing the transferred data, replicating the directory structure of `/repo/roman-desc-sims` at NERSC.
- [x] Create a new data repository at CSD3, with `butler create`, nominally using the postgres db.
- [x] Ingest calibration products, refcats, and skymaps.
- [x] Import the registry info for the transferred data into the CSD3 repo, using a special import script so that the prepared repo directory structure can be used as-is.
- [x] Rebuild the chained and tagged collections.
- [x] Run test queries and test pipelines.

I've already done all of these steps for small test repos using sqlite3 at NERSC and at CSD3.   I will put copies of the final export and import scripts in this github repo, for the record.

**Comment by jchiang87** [comment]
The repository has been set up using the postgres db and is operational.   From bash, set the environment variable
```
DAF_BUTLER_REPOSITORY_INDEX=/rds/project/rds-rPTGgs6He74/desc/roman-rubin-data/shared/data-repos.yaml
```
and the repo will be available as `/repo/roman-desc-sims`.
